# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-latest'
  #name: 'Default'

variables:
  configuration: 'Debug'

steps:

#%USERNAME%
- ${{ if ne('test', 'Windows_NT') }}:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        echo 'export TEST=value' > add_test_env.sh
        . ./add_test_env.sh
        echo $TEST

- task: CMakem@1
  inputs:
    workingDirectory: 'CPPTest'
    cmakeArgs: -DCMAKE_BUILD_TYPE=Release -DTEST_CMAKE_TASK=$0;test -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_INSTALL_PREFIX=/vstsdrive/_work/7/a/LLVMToolchain -DLLVM_ENABLE_PROJECTS=clang;lld;lldb
    runInsideShell: true
