# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master


#pool:
  #vmImage: 'Windows-latest'
#  name: 'default'


#variables:
 # configuration: 'Debug'
  #Build.ArtifactStagingDirectory: 'D:/Test/arttest'
  #certificate: 'test_cert.p12'
#- group: group1

jobs:
- job: Job1
  pool:
    name: 'v-egbryz'
    demands:
      - agent.name -equals O21
  steps:
  - task: JenkinsQueueJoba@2
    inputs:
      serverEndpoint: 'Jenkins1'
      jobName: 'TestFolder/Repro1'
      captureConsole: true
      capturePipeline: false
      isParameterizedJob: true
      jobParameters: > 
        param=Repro1

        sleep=30

- job: Job2
  pool:
    name: 'v-egbryz'
    demands:
      - agent.name -equals O21a
  steps:
  - task: JenkinsQueueJoba@2
    inputs:
      serverEndpoint: 'Jenkins1'
      jobName: 'TestFolder/Repro2'
      captureConsole: true
      capturePipeline: false
      isParameterizedJob: true
      jobParameters: > 
        param=Repro2
        
        sleep=30

