# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  configuration: 'Debug'

steps:

- script: |
    echo "testing variables"
    echo "printing variable"
    echo $(test)
    echo $TEST
    echo $env:TEST
  displayName: 'Show variable value'


- script: |
    cd ./CPPTest
    cmake -B build-script -DTEST_CMAKE_TASK=$TEST
- task: CMake@1
  inputs:
    workingDirectory: 'CPPTest'
    cmakeArgs: -DTEST_CMAKE_TASK=$TEST