# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  #vmImage: 'Ubuntu-latest'
  name: 'Default'

variables:
  configuration: 'Debug'
  AZP_BASHV3_OLD_SOURCE_BEHAVIOR: true


steps:
- task: JenkinsQueueJob@2
  inputs:
    serverEndpoint: 'Jenkins1'
    jobName: 'TestPipeline'
    captureConsole: true
    capturePipeline: true
    isParameterizedJob: false
    jobParameters: 'paraparaparametr==true'
