# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  #vmImage: 'Windows-latest'
  name: 'Default'


variables:
  configuration: 'Debug'
  Build.ArtifactStagingDirectory: 'C:/localagent/_work/1/s/test'

steps:
- task: Mavenm@3
  inputs:
    mavenPomFile: 'D:\Test\Maven\DeepSpace\pom.xml'
    publishJUnitResults: false
    #testResultsFiles: 'D:\Test\Maven\surefire-reports\TEST-*.xml'
    #codeCoverageToolOption: 'Cobertura'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

#- task: SSH@0
#  inputs:
#    sshEndpoint: 'SSH local v-alias'
#    runOptions: 'commands'
#    commands: 'dir \\Products\Public'
#    readyTimeout: '20000'

#- task: CopyFilesOverSSH@0
#  inputs:
#    #sshEndpoint: 'ssh local admin'
#    sshEndpoint: 'SSH local v-alias'
#    sourceFolder: 'D:\Test\'
#    contents: 'test.txt'
#    targetFolder: '\\fs\Public\egor.bryzgalov\test'
#    #targetFolder: 'Z:\egor.bryzgalov\test'
#    #targetFolder: '\\localhost\d$\Test\target'
#    isWindowsOnTarget: true
#    cleanTargetFolder: true
#    readyTimeout: '20000'
#    overwrite: true

#- task: ArchiveFiles@2
#  inputs:
##    rootFolderOrFile: 'C:\localagent\_work\1\s'
#    includeRootFolder: true
#    archiveType: 'zip'
#    archiveFile: 'C:\localagent\_work\1\art.zip'
#    replaceExistingArchive: true

#- task: ArchiveFiles@2
##  inputs:
 #   rootFolderOrFile: 'C:\localagent\_work\1\s'
#    includeRootFolder: true
#    archiveType: 'zip'
#    archiveFile: 'C:\localagent\_work\1\artnew.zip'
#    replaceExistingArchive: true

#- task: PublishBuildArtifacts@1
#  inputs:
#    PathtoPublish: 'C:\localagent\_work\1\art.zip'
#    ArtifactName: 'One'
#    publishLocation: 'Container'
#    TargetPath: 'C:\localagent\_work\_newtemp'
  
#- task: PublishBuildArtifacts@1
#  inputs:
#    PathtoPublish: 'C:\localagent\_work\1\artnew.zip'
##    ArtifactName: 'ONE'
##    publishLocation: 'Container'
#   TargetPath: 'C:\localagent\_work\_newtemp'

#- task: PublishBuildArtifacts@1
#  inputs:
#    PathtoPublish: 'D:\Test\MyArtifacts'
#    ArtifactName: 'MyArtifact'
#    publishLocation: 'Container'