# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-latest'
  #name: 'Default'

variables:
  configuration: 'Debug'
  AZP_BASHV3_OLD_SOURCE_BEHAVIOR: true

steps:

- task: CMakem@1
  inputs:
    workingDirectory: 'CPPTest'
    cmakeArgs: -DCMAKE_SHELL=false -DTEST_ONE=one;two -DTEST_TWO=/one/two/three -DTEST_WIN_VARIABLE=test -DTEST_VARIABLE=test
    runInsideShell: false
- task: CMake@1
  inputs:
    workingDirectory: 'CPPTest'
    cmakeArgs: -DCMAKE_SHELL=true -DTEST_ONE=one;two -DTEST_TWO=/one/two/three -DTEST_VARIABLE=$USER -DTEST_WIN_VARIABLE=%OS%
    runInsideShell: true
