# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  #name: 'Default'

variables:
  configuration: 'Debug'

steps:

- script: |
    echo "testing variables"
    echo "printing variable"
    echo $(configuration)
    echo $CONFIGURATION
    echo $env:CONFIGURATION
  displayName: 'Show variable value'

- script: |
    echo emscripten for $USER is $EMSCRIPTEN

- script: |
    cd ./CPPTest
    echo "build-script -DTEST_CMAKE_TASK=$USER"
    cmake -B build-script -DTEST_CMAKE_TASK=$USER

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'echo "$USER"'
    
- task: CMakem@1
  inputs:
    workingDirectory: 'CPPTest'
    #cmakeArgs: '-DTEST_CMAKE_TASK="$USER"'
    cmakeArgs: '-DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_INSTALL_PREFIX=/vstsdrive/_work/7/a/LLVMToolchain -DLLVM_ENABLE_PROJECTS="clang;lld;lldb"'