# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master


pool:
  vmImage: 'Windows-latest'
  #name: 'default'


variables:
  configuration: 'Debug'
  #Build.ArtifactStagingDirectory: 'D:/Test/arttest'
  #certificate: 'test_cert.p12'
#- group: group1
steps:

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $PAT="$(PAT)"
      $branch="$(branch)"

      git checkout -b test10
      Write-Host 'Trying to pull the remote branch:'
      git pull https://$PAT@github.com/egor-bryzgalov/TestCpp.git $branch
      if (-not $?) {
        Write-Host 'Failed to pull the remote branch. This is expected if the remote branch doesn't exist.
      }
      git push https://$PAT@github.com/egor-bryzgalov/TestCpp.git $branch
