# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-latest'
  #name: 'Default'

variables:
  configuration: 'Debug'

steps:

#%USERNAME%
- ${{ if ne(variables['Agent.OS'], 'Windows_NT') }}:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        export TESTVAR=value > add_test_env.sh
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        printenv

- task: CMake@1
  inputs:
    workingDirectory: 'CPPTest'
    cmakeArgs: -DCMAKE_SHELL=true -DTEST_ONE=one;two -DTEST_TWO=/one/two/three -DTEST_VARIABLE=$env.USER -DTEST_WIN_VARIABLE=%OS%
    #runInsideShell: true
