# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  #vmImage: 'Windows-latest'
  name: 'Default'


variables:
  configuration: 'Debug'
  Build.ArtifactStagingDirectory: 'C:/localagent/_work/1/s/test'

steps:

#- task: InstallSSHKeym@0
#  inputs:
#    knownHostsEntry: 'github.com,140.82.118.3 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=='
#    sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDbmkC84yRv0uda1sa01IpjVG4AMGFfj9GYLktNhL8+q1uwMKkrasghOpvIv3M1gevCQtsVtb0Pl7PPSApK3/h6hjHVIe86iVh3g5nLUY4aXqX8z46RMYGUPtCDqKoiFxNmuB3gYEXC/tqt5lqP8K/1prOcpOcIIVj9q1YxtKoCJEY4qtidYhBW3B4SyOq3WmumriNqJek6/QFX8NvErTANqfyyDARbj7AfyHKOczkJguRrX4PK3TIu6b1RItMUhVZjjkFSRuo5bnQpvayt3mEpMpTHEQeBqV9FVhx9JfRXZ4Hj4JhDnURLZcKI1xyegb9yvTdOt1/OtZgmDwloLMbRhWiwdQiTeElGahu8Ga3FGWCkf4tDyOFjJsCbujtpK7KXMyzBIwztoN3uDlAcp69TfmnK+neEThvyXE9uRNlmEiJg9guJupVDJdaKPIINdWMJoFH/ry1+b2uRgYAxeME+u93R+TOQzk3FABMJu1OPKogwe9eAOHrA8ifqXj9v5D0= v-egbryz@o21'
#    sshKeySecureFile: 'sshnokey'
#    addEntryToConfig: true
#    configHostAlias: 'test-alias'
#    configUser: 'testuser'
#    configHostname: 'github.com'

#- task: InstallSSHKeym@0
#  inputs:
#    knownHostsEntry: 'github.com,140.82.118.3 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=='
#    sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC4FtRnl/TOUCEnZY0LzC38oLkmk3jaa5Kpp6MokbzXbxraxruZpEovBrMd5fE4mg13DsIjLqboc9880EpQUPlq4HRx/yipqkv1Z/FhL5WlBq7QQxuAo9KJuiE1xw5/w+MuB3giiDKjvkq03rkqYBbYjLsR/Xtt6Eh3sJcvhWt6HC9VPjQOPI2yNm6005wc178EIaARZpen+BcTUYqWjBSgFQeKD4ap9XKj+ixys8+7who1cm0pOQJpdVWTZ++55zt1xaz13dB5sIYPz7gXxrc/Np0MlppkaP16EvxUV1jETMl/h0k99pQQ1mHtJQxXEODsyNkqk86WQbN/etuZdfMl europe\v-egbryz@o21'
#    sshKeySecureFile: 'sshwithkey'
#    sshPassphrase: passphrase
#    addEntryToConfig: false
#    configHostAlias: 'test-alias'
#    configUser: 'testuser'
#    configHostname: 'github.com'

#- task: InstallSSHKeym@0
#  inputs:
#    knownHostsEntry: 'github.com,140.82.118.4 ssh-rsa TESTB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=='
#    #sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCjL+fv9UC/5qF4nOiMkBrSOGYaIU2BIJNnZSWnXLtudLsoPWTUotA1ACDP5pjDV9PEdSiHkdni+nTdna/jSBEHIz1rTnhUXwRgndxTnjRqHzwMd4r7N9LnYuSuMb20FJE4ndvrYWgP/kaWe11jxDe12CNUaxUBfoY/taHlsTS6M8mfGcHytGcqII2RgN4sWzBAvN1ybsnqySr/yYUk0Y0bnjrmsiOIN9EO4s4+LYOGXC0iJH31P+a/bT7eeWoBgpQDZQ5szxvcTpKFxrgK/lF3hJEXSEwXtWbdY2GK0p7bVVEaZDRfN0/8yQP0WhvIGSrZybH3s/ppMRNRN6pFxHLcjHIIAK1UleKGzOc/sVlVBOQ267MQZtF6CtGw167iCAMywXt6YOSgK1f15BXwCSLvvF1irdw/L5fm1urBHJ7p+6a2CjE+K3dko8Hm1Kz2KHamIUFlDlMgwEvUUnVGAqsqL7B249tf9i11n3GqsQrTAXuvQ4BMvwQJzroMV/caXLE= v-egbryz@o21'
#    sshKeySecureFile: 'sshnokey2'
#    addEntryToConfig: true
#    configHostAlias: 'test-aliasz'
#    configUser: 'testuser'
#    configHostname: 'github.com'

#- script: ssh -T git@github.com



#- task: InstallSSHKey@0
#  inputs:
#    knownHostsEntry: 'github.com,140.82.118.4 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=='
#    sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDx0xHmF8pbr0GWTvXCXDoUj62QW+gY41V2Y++bbLpl7a9qdxRTTaH9CgkWhyrJe1Ca+0IdNVk5Zlgpk81rTYUm21o6tQ25xuMjb8MBYRxEFDxqu64xlKmbciGAs+9QKWrlirkIu2kdhIbYfy5fBPrmz3iil7Ginzz0zepGVGk9w/rGdup8Wjvr/IoDqDGmvvsXzKe57hPM2p1aDdRsAOETxRqOEmqzO+XOwzSqBucbhcmLsauBOP6Zmnf0rpGcOhZpm6nblWWkkvkuxdOFA7CB5TZNW1v3nwplLEp+NUFbbSOcLnPVtoZ5cAExjb79bWIRJp4CqYw/tVEFtdASEMmF v-egbryz@o21'
#    sshKeySecureFile: '

#- task: InstallSSHKey@0
#  inputs:
#    knownHostsEntry: 'github.com,140.82.118.4 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=='
#    sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDz+R5eRVTKnip5KBMti0bRVtegqLfhN3Pe3xcfK3+kimq/ZKMDU0kJFNbKW06Okfk7VN8kpgx1/egglwFrfKocM6zTgNFVX9K6PmM0zC6lNo70wYMhcwS4/WCHEzmvrwIGC1ZGtwaQn1uwfF8eqfcsK+UH9mo6FSZsJtbF0CLSWZlLzfpSbmPKStZL5eKhuPwlWKTD7qupWmuuCrdkjBAnMZ4QNHA8C/w4CkpAjU3lClZ5xeQXObEEwJnHCxtdHzdmRXuLv1xVCJUT6uWMabQ3IbKKeuklrWRTXiSxYJDo04CIv3XyXQDOr9DUfi0RBHNQaMa7ThaDOeprtLBt14U/ v-egbryz@o21'
#    sshKeySecureFile: 'newssh'
#- task: PublishPipelineArtifact@1
#  inputs:
#    targetPath: 'C:\agent\_work\2\s'
#    artifact: 'PipelineItem'
#    publishLocation: 'pipeline'

#- task: ArchiveFiles@2
#  inputs:
#    #rootFolderOrFile: 'C:\agent\_work\2\s'
#    rootFolderOrFile: 'd:\a\1\s'
#    includeRootFolder: true
#    archiveType: 'zip'
##    archiveFile: 'C:\agent\_work\2\s\archive.zip'
 #   replaceExistingArchive: true
 #   verbose: true

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'C:/localagent/_work/1/s'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: 'C:/localagent/_work/1/s/art.zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'C:/localagent/_work/1/s/art.zip'
    ArtifactName: 'LowerCase'
    publishLocation: 'Container'
    #TargetPath: 'C:\localagent\_work\_temp'