# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master


pool:
  vmImage: 'Windows-latest'
  #name: 'default'


variables:
  configuration: 'Debug'
  #Build.ArtifactStagingDirectory: 'D:/Test/arttest'
  #certificate: 'test_cert.p12'
#- group: group1

steps:

#- task: CMakem@1
#  inputs:
##    workingDirectory: './CPPTest'
#    cmakeArgs: -DCMAKE_SHELL=true -DTEST_ONE=one;two -DTEST_TWO=/one/two/three -DTEST_VARIABLE=$USER -DTEST_WIN_VARIABLE=%OS%
#    runInsideShell: true

#- task: JavaToolInstallerm@0
#  inputs:
#    versionSpec: '15'
#    jdkArchitectureOption: 'x64'
#    jdkSourceOption: 'LocalDirectory'
#    jdkFile: 'D:\Downloads\openjdk-15.0.1_windows-x64_bin.zip'
#    jdkDestinationDirectory: 'D:\Test\JDK_15'
#    cleanDestinationDirectory: true

  
- task: JavaToolInstallerm@0
  inputs:
    versionSpec: '15'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'AzureStorage'
    azureStorageAccountName: 'kejteststorage'
    azureContainerName: 'jdk-test'
    azureCommonVirtualFile: 'openjdk-15.0.1_windows-x64_bin.zip'
    jdkDestinationDirectory: './'
    cleanDestinationDirectory: false
    azureResourceManagerEndpoint: 'TEST CIX'