# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  #vmImage: 'Ubuntu-latest'
  name: 'Default'


variables:
  configuration: 'Debug'
  AZP_BASHV3_OLD_SOURCE_BEHAVIOR: true


steps:

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'Alex SSH server'
    sourceFolder: 'C:\agent\_work\_tasks\CICDSampleMockDemo_6f92fd8f-3076-40e1-9706-315df19c79f1'
    contents: '**'
    readyTimeout: '20000'
#/home/vsts/work
#- task: Bash@3
#  inputs:
#    targetType: 'inline'
#    script: 'ls /home/vsts/work/_tasks/CICDSampleMockDemo_6f92fd8f-3076-40e1-9706-315df19c79fc/1.0.1'
#d:\a\_tasks
#- task: JenkinsQueueJobm@2
#  inputs:
#    serverEndpoint: 'Jenkins1'
#    jobName: 'TestPipeline'
#    captureConsole: true
#    capturePipeline: true
#    isParameterizedJob: true
#    #jobParameters: 'tess="somestring"'
#    jobParameters: 'test=true'

#- task: CICDSampleMockDemo@1
#  inputs:
#    appName: 'asdasd'
#    buildAliasName: 'asdasd'
#    buildDropLocation: '$(Build.Binariesdirectory)'
#    sandboxName: 'asdasd'
