# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master


pool:
  vmImage: 'Windows-latest'
  #name: 'default'


variables:
  configuration: 'Debug'
  #Build.ArtifactStagingDirectory: 'D:/Test/arttest'
  #certificate: 'test_cert.p12'
#- group: group1
steps:
- bash: |
    echo $PATH
- task: UsePythonVersionm@0
  displayName: 'Do not append PATH'
  name: 'Test1'
  inputs:
    versionSpec: '3.8.x'
    addToPath: false
    architecture: 'x64'

- bash: |
    echo $PATH
    if grep -q "Python/3.8" <<< "$PATH"; then
        echo 'A value was added to PATH but should not have to'
        exit 1
    else
        echo 'PATH was not appended. Test passed'
    fi
  displayName: 'Check that PATH was not appended'

- pwsh: |
    if (Test-Path "$(Test1.pythonLocation)") {
        Write-Host 'Python location has been set'
    } else {
      throw 'Python location has not been set'
    }
    echo 'pythonLocation=$(Test1.pythonLocation)'

    $pattern = 'Python/3.8'
    if ($env:OS -like '*Windows*') {
      $pattern = 'Python\3.8'
    }

    if ('$(Test1.pythonLocation)' -like "*$pattern*") {
      Write-Host 'Python location is OK'
    } else {
      throw 'Python location is wrong'
    }
  displayName: 'Test output variable'

- task: UsePythonVersionm@0
  displayName: 'Append PATH'
  name: 'Test2'
  inputs:
    versionSpec: '3.8.x'

- bash: |
    if ! grep -q "Python/3.8" <<< "$PATH";
    then
        echo 'PATH has not been appended'
        exit 1
    else
        echo 'PATH has been appended'
    fi
  displayName: 'Test appending PATH'
